baseURL = 'https://zft9xgy.github.io/zero'
fontbody = 'Droid Sans'
fontcode = 'Fira Mono'
googlefonts = ["Droid Sans", "Fira Mono"]
languageCode = 'es-es'
theme = 'PaperMod'
title = 'Zero'

[menu]
[[menu.main]]
name = 'tags'
pageRef = '/tags'
weight = 20
[[menu.main]]
name = 'all posts'
pageRef = '/all-posts'
weight = 30

[params]
[params.homeInfoParams]
Content = "El que empieza un camino, tiene el 50% hecho."
Title = "Vamos a ello."

[[params.socialIcons]]
name = 'github'
url = 'https://github.com/zft9xgy'

[[params.socialIcons]]
name = 'email'
url = 'zft9xgy@proton.me'

[[params.socialIcons]]
name = 'linkedin'
url = 'https://www.linkedin.com/in/rafael-cosquiere/'
