baseURL = 'https://zft9xgy.github.io/zero'
languageCode = 'es-es'
theme = 'PaperMod'
title = 'Zero'

[menu]
[[menu.main]]
name = 'tags'
pageRef = '/tags'
weight = 20
[[menu.main]]
name = 'all posts'
pageRef = '/all-posts'
weight = 30
